---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  labels:
    backstage.io/kubernetes-id: flask-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
        backstage.io/kubernetes-id: flask-frontend
    spec:
      containers:
      - name: ubuntu
        image: portainer/portainer-ee:latest
        
        